services:
  laravel:
    container_name: laravel-app
    working_dir: /var/www
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    environment:
        - PUID=${PUID:-$(id -u)}
        - PGID=${PGID:-$(id -g)}
    volumes:
      - .:/var/www
    depends_on:
      - pgsql

  pgsql:
    image: postgres:15
    container_name: pgsql
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - .:/var/www
      - ssl-certs:/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - pgsql
      - laravel

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

volumes:
  postgres-volume:
  ssl-certs:
